export type Location = { en: string; ar: string };

export const dubaiLocations: Location[] = [
  { en: "Al-Qusais", ar: "القصيص" },
  { en: "Muhaisnah", ar: "محيصنة" },
  { en: "Al-Mizhar", ar: "المزهر" },
  { en: "Mirdif", ar: "مردف" },
  { en: "Jumeirah Beach", ar: "شاطئ جميرا" },
  { en: "Dubai Marina", ar: "دبي مارينا" },
  { en: "Sheikh Zayed Road", ar: "شارع الشيخ زايد" },
  { en: "Media City", ar: "مدينة الإعلام" },
  { en: "Barsha Heights", ar: "برشا هايتس" },
  { en: "Dubai Internet City", ar: "مدينة دبي للإنترنت" },
  { en: "The Greens", ar: "الغرينز" },
  { en: "Emirates Living", ar: "إميريتس ليفينج" },
  { en: "The Palm Jumeirah", ar: "نخلة جميرا" },
  { en: "The Gardens", ar: "الحدائق" },
  { en: "Jumeirah Park", ar: "جميرا بارك" },
  { en: "Jumeirah Island", ar: "جزيرة جميرا" },
  { en: "Jumeirah Lakes Tower", ar: "أبراج بحيرات جميرا" },
  { en: "Dubai Production City", ar: "مدينة دبي للإنتاج" },
  { en: "Jumeirah Golf Estates", ar: "جميرا جولف إستيتس" },
  { en: "Arabian Ranches", ar: "المرابع العربية" },
  { en: "Dubai Investment Park", ar: "مجمع دبي للاستثمار" },
  { en: "Falcon City of Wonders", ar: "مدينة الصقور" },
  { en: "The Villa", ar: "الفيلا" },
  { en: "Dubai Land", ar: "دبي لاند" },
  { en: "Dubai Silicon Oasis", ar: "واحة دبي للسيليكون" },
  { en: "Discovery Gardens", ar: "ديسكفري غاردنز" },
  { en: "International City", ar: "المدينة الدولية" },
  { en: "Um Suqeim", ar: "أم سقيم" },
  { en: "Al Quoz", ar: "القوز" },
  { en: "Al Safa", ar: "الصفا" },
  { en: "Business Bay", ar: "الخليج التجاري" },
  { en: "Downtown Dubai", ar: "وسط مدينة دبي" },
  { en: "Jumeirah", ar: "جميرا" },
  { en: "DIFC", ar: "مركز دبي المالي العالمي" },
  { en: "Al Satwa", ar: "السطوة" },
  { en: "Bur Dubai", ar: "بر دبي" },
  { en: "Oud Mehta", ar: "عود ميثاء" },
];

export const abuDhabiLocations: Location[] = [
  { en: "Delma St", ar: "شارع دلما" },
  { en: "Abu Dhabi", ar: "أبوظبي" },
  { en: "Al Karamah Street", ar: "شارع الكرامة" },
  { en: "Reem Island", ar: "جزيرة الريم" },
  { en: "Khalifa City A", ar: "مدينة خليفة أ" },
  { en: "Khalifa City B", ar: "مدينة خليفة ب" },
  { en: "Al Bandar", ar: "البندر" },
  { en: "Al Zeina", ar: "الزينة" },
  { en: "Al Reef", ar: "الريف" },
  { en: "Al Raha Beach", ar: "شاطئ الراحة" },
  { en: "Musaffah", ar: "مصفح" },
  { en: "Mohamed Bin Zayed City", ar: "مدينة محمد بن زايد" },
  { en: "Al Ghadeer", ar: "الغدير" },
];

export const uaeLocations: Location[] = [
  { en: "Ajman", ar: "عجمان" },
  { en: "Sharjah", ar: "الشارقة" },
  { en: "UAQ", ar: "أم القيوين" },
  { en: "RAK", ar: "رأس الخيمة" },
  { en: "Fujairah", ar: "الفجيرة" },
  { en: "Al Ain", ar: "العين" },
];
